version: '3.9'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - 'django-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=python_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    networks:
      python-networks:

  web:
    build: .
    command: 'python manage.py runserver 0.0.0.0:8000'
    restart: always
    volumes:
      - '.:/code'
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      python-networks:

volumes:
  django-data: {}
networks:
  python-networks: