services:
  db:
    image: postgres
    volumes:
      - django-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=python_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=python_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
volumes:
  django-data: {}
